name: Docker Image CI

on:
    push:
        branches:
            - testing
            - master
            - 'releases/**'
    pull_request:
        branches:
            - testing

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    SERVICE: liatrio-my-name-chris
    REGION: us-west4

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker Image
          run: docker build . --file Dockerfile --tag liatrio-my-name-chris

        - name: Run Container
          run: docker run -d -p 80:80 --name golang-server liatrio-my-name-chris:latest

        - name: run tests
          uses: liatrio/github-actions/apprentice-action@v1.0.0

