name: Docker Image CI

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag liatrio-my-name-chris

    - name: Run Container
      run: docker run -d -p 80:80 --name golang-server liatrio-my-name-chris:latest

    - name: Echo Version Number
      run: echo Version number is ${{ vars.VERSION }}.${{github.run_number }}

    - name: Push Image to Dockerhub
      run: |
        docker login -u kristoffjohnson -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker tag liatrio-my-name-chris:latest kristoffjohnson/liatrio-my-name-chris:0${{ vars.VERSION }}.${{github.run_number }}
        docker push kristoffjohnson/liatrio-my-name-chris:0${{ vars.VERSION }}.${{github.run_number }}
        docker tag liatrio-my-name-chris:latest kristoffjohnson/liatrio-my-name-chris:latest
        docker push kristoffjohnson/liatrio-my-name-chris:latest
      
    - name: run tests
      uses: BipbopBohnfon/github-actions/apprentice-action@master
