name: Deploy

on:
    push:
        branches:
            - testing

#on:
#    pull_request_target:
#        branches:
#            - master
#        types:
#            - closed
#            - 'releases/**'
env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GCP_SERVICE_ACCOUNT: 'githubaction@gen-lang-client-0653191359.iam.gserviceaccount.com'
    SERVICE: liatrio-my-name-chris
    REGION: us-west1

jobs:
    deploy:
        #if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker Image
          run: docker build . --file Dockerfile --tag liatrio-my-name-chris

        - name: Run Container
          run: docker run -d -p 80:80 --name golang-server liatrio-my-name-chris:latest

        - name: Echo Version Number
          run: echo Version number is ${{ vars.VERSION }}.${{github.run_number }}

        - name: Push Image to Dockerhub
          run: |
            docker login -u kristoffjohnson -p ${{ secrets.DOCKER_HUB_TOKEN }}
            docker tag liatrio-my-name-chris:latest kristoffjohnson/liatrio-my-name-chris:0${{ vars.VERSION }}.${{github.run_number }}
            docker push kristoffjohnson/liatrio-my-name-chris:0${{ vars.VERSION }}.${{github.run_number }}
            docker tag liatrio-my-name-chris:latest kristoffjohnson/liatrio-my-name-chris:latest
            docker push kristoffjohnson/liatrio-my-name-chris:latest

        - name: Google Cloud Auth
          uses: google-github-actions/auth@v1
          with:
              credentials_json: ${{ secrets.GCP_CREDENTIALS }}
              project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Google Cloud Setup
          uses: google-github-actions/setup-gcloud@v1
          
        - name: Configure Docker
          run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

        - name: Deploy to Cloud Run
          run: |-
            gcloud run deploy ${{ env.SERVICE }} \
              --project ${{ secrets.GCP_PROJECT_ID }} \
              --region ${{ env.REGION }} \
              --image docker.io/kristoffjohnson/liatrio-my-name-chris:0${{ vars.VERSION }}.${{github.run_number }} \
              --platform managed \
              --allow-unauthenticated \
              --port 80
